# Generated by Django 5.2.8 on 2025-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('salary', models.FloatField(default=0.0)),
                ('address', models.TextField(default='')),
            ],
        ),
    ]
